/**
 * Span-coverage harness for the click-to-edit PDF preview.
 *
 * Verifies, for every document in the catalog and every sample fixture:
 *   1. Each generator records spans only for keys declared in
 *      src/services/pdfFieldSchema.ts (no invented keys).
 *   2. Every schema field whose value is non-empty has at least one
 *      clickable span in its document (so all displayed data is editable).
 *   3. All spans lie within the US Letter page bounds.
 *
 * Run with:  npx tsx scripts/test-pdf-spans.ts
 */
import { JOB_DOCUMENTS } from '../src/services/documentCatalog';
import { generateDocWithSpans } from '../src/services/pdfService';
import { getPdfFieldSchema } from '../src/services/pdfFieldSchema';
import { SAMPLE_WATER, SAMPLE_STORM, SAMPLE_FIRE } from './fixtures';
import type { RestorationJobData } from '../src/types/jobData';

let failures = 0;
let checks = 0;
function check(name: string, condition: boolean, detail = '') {
  checks++;
  if (condition) {
    console.log(`  OK    ${name}`);
  } else {
    failures++;
    console.log(`  FAIL  ${name}${detail ? `  -> ${detail}` : ''}`);
  }
}

function getPath(obj: unknown, path: string): unknown {
  return path.split('.').reduce<unknown>((o, k) => (o == null ? o : (o as Record<string, unknown>)[k]), obj);
}

function hasValue(v: unknown): boolean {
  if (v == null) return false;
  if (typeof v === 'string') return v.trim().length > 0;
  if (typeof v === 'number') return !Number.isNaN(v);
  return true; // booleans and anything else present
}

const SAMPLES: Array<[string, RestorationJobData]> = [
  ['SAMPLE_WATER', SAMPLE_WATER],
  ['SAMPLE_STORM', SAMPLE_STORM],
  ['SAMPLE_FIRE', SAMPLE_FIRE],
];

async function main() {
  for (const doc of JOB_DOCUMENTS) {
    console.log(`\n=== ${doc.id} (${doc.title}) ===`);
    const schema = getPdfFieldSchema(doc.id);
    if (schema.length === 0) {
      console.log('  WARN  no editable-field schema for this document');
      continue;
    }
    const schemaKeys = new Set(schema.map((f) => f.key));

    for (const [sampleName, sample] of SAMPLES) {
      const { bytes, spans } = await generateDocWithSpans(doc.generator, sample);
      check(`${sampleName}: generated bytes`, bytes.length > 500, `got ${bytes.length}`);
      const spanKeys = new Set(spans.map((s) => s.key));

      // 1. No invented keys — every span must map to a schema field.
      for (const s of spans) {
        if (!schemaKeys.has(s.key)) {
          check(`${sampleName}: span key in schema: ${s.key}`, false, 'not in pdfFieldSchema');
        }
      }

      // 2. Every non-empty schema field must be clickable somewhere.
      //    (drawerOnly fields are edited from the fields drawer, not spans.)
      for (const f of schema) {
        if (f.drawerOnly) continue;
        const effectiveKeys = f.parts ? f.parts.map((p) => p.field) : [f.key];
        const valuePresent = effectiveKeys.some((k) => hasValue(getPath(sample, k)));
        if (valuePresent && !spanKeys.has(f.key)) {
          check(`${sampleName}: span for non-empty field: ${f.key}`, false, 'missing span');
        }
      }

      // 3. All spans inside US Letter bounds (612 x 792) on a valid page.
      for (const s of spans) {
        const inBounds =
          s.page >= 1 &&
          s.x >= -1 &&
          s.y >= -1 &&
          s.x + s.width <= 613 &&
          s.y + s.height <= 793;
        if (!inBounds) {
          check(
            `${sampleName}: span bounds: ${s.key} p${s.page}`,
            false,
            `x=${s.x.toFixed(1)} y=${s.y.toFixed(1)} w=${s.width.toFixed(1)} h=${s.height.toFixed(1)}`
          );
        }
      }

      const missing = schema
        .filter((f) => {
          if (f.drawerOnly) return false;
          const effectiveKeys = f.parts ? f.parts.map((p) => p.field) : [f.key];
          return effectiveKeys.some((k) => hasValue(getPath(sample, k))) && !spanKeys.has(f.key);
        })
        .map((f) => f.key);
      const unknown = spans.filter((s) => !schemaKeys.has(s.key)).map((s) => s.key);

      console.log(
        `  ${sampleName}: ${spans.length} spans, ${missing.length} missing, ${unknown.length} unknown`
      );
    }
  }

  console.log(`\n${checks} checks, ${failures} failures`);
  process.exit(failures > 0 ? 1 : 0);
}

main().catch((err) => {
  console.error('Span test crashed:', err);
  process.exit(1);
});
